# Solo para alertas de seguridad - configurado desde GitHub UI
# Para activar solo PRs de seguridad, ve a Settings > Security > Dependabot:
# ✅ Dependabot alerts: ENABLED
# ✅ Dependabot security updates: ENABLED
# ❌ Dependabot version updates: DISABLED
#
# Este archivo está comentado para evitar actualizaciones automáticas de versiones

# version: 2
# updates:
#   - package-ecosystem: "npm"
#     directory: "/javascript"
#     schedule:
#       interval: "weekly"
